Create taurus machine type
* scripts/TLCC/scr_run.in

  Rollback the changes to TLCC/scr_run.in to the original state.

* scripts/taurus/*

  Duplicate TLCC machine as taurus machine. Since now on all
  configuration related to load balancing will be done for taurus
  machine type.

* m4/x_ac_machine.m4
* src/scr_env.c

  Update other files, which should be aware of new machine type.

diff --git a/scripts/taurus/scr_run.in b/scripts/taurus/scr_run.in
--- a/scripts/taurus/scr_run.in
+++ b/scripts/taurus/scr_run.in
@@ -96,6 +96,8 @@ fi
 
 # enter the run loop
 down_nodes=""
+SLURM_HOSTFILE=""
+node_distribution="--distribution=block"
 attempts=0
 runs=${SCR_RETRIES:-0}
 runs=$(($runs + 1))
@@ -180,7 +182,7 @@ while [ 1 ] ; do
   $bindir/scr_log_event -T "RUN STARTED" -N "Job=$jobid, Run=$attempts" -S $start_secs
 
   if [ $use_scr_watchdog -eq 0 ]; then
-     srun --nodelist $script_node $exclude "$@"
+     srun --nodelist $script_node $exclude $node_distribution "$@"
   else
     echo "$prog: Attempting to start watchdog process."
      # need to get job step id of the srun command
@@ -209,6 +211,40 @@ while [ 1 ] ; do
 
   # log stats on the latest run attempt
   $bindir/scr_log_event -T "RUN ENDED" -N "Job=$jobid, Run=$attempts" -S $end_secs -L $run_secs
+
+  # Did we stop because of migration?
+  $bindir/scr_migration --dir $prefix;
+  if [ $? == 0 ] ; then
+    echo "$prog: Migration condition detected, restarting run."
+    if [ -f $prefix/.scr/balancer.scr ]
+    then
+      SLURM_HOSTFILE="$prefix/.scr/balancer.scr"
+      node_distribution="--distribution=arbitrary -w $SLURM_HOSTFILE"
+    else
+      SLURM_HOSTFILE=""
+      node_distribution="--distribution=block"
+    fi
+    # scavenge files from cache to parallel file system
+    $bindir/scr_postrun -p $prefix
+    if [ $? -ne 0 ] ; then
+      echo "$prog: ERROR: Command failed: scr_postrun -p $prefix"
+    fi
+
+    # prepare checkpoint cache
+    $bindir/scr_prerun -p $prefix
+    if [ $? -ne 0 ] ; then
+      echo "$prog: ERROR: Command failed: scr_prerun -p $prefix"
+      exit 1
+    fi
+
+    # start background scr_transfer processes (1 per node) if async flush is enabled
+    if [ "$SCR_FLUSH_ASYNC" == "1" ] ; then
+      nnodes=`$bindir/scr_glob_hosts -c -h $SCR_NODELIST`
+      srun -W 0 -n${nnodes} -N${nnodes} $bindir/scr_transfer $cntldir/transfer.scrinfo &
+    fi
+
+    continue
+  fi
 
   # any retry attempts left?
   if [ $runs -gt -1 ] ; then
